/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type RoomStatus = "finished" | "playing" | "tutorial" | "waiting";

export type RoomType = "private" | "public";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CategoryLetterHistory {
  categoryName: string;
  id: Generated<number>;
  letter: string;
  playerId: string;
  usedAt: Generated<Timestamp | null>;
}

export interface CategoryStats {
  categoryName: string;
  deadRounds: Generated<number>;
  id: Generated<number>;
  successfulAttempts: Generated<number>;
  totalAttempts: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
}

export interface GameSessionStats {
  createdAt: Generated<Timestamp | null>;
  finalGrandWordSubmitted: string | null;
  firstGrandAttemptTime: Timestamp | null;
  gameEndTime: Timestamp | null;
  gameMode: string;
  gameStartTime: Timestamp;
  grandAttemptCount: Generated<number>;
  id: Generated<number>;
  lettersAtFirstGrandAttempt: number | null;
  miniCategoriesSeen: Generated<number>;
  playerId: string;
  playersCount: Generated<number>;
  playerUsername: string | null;
  possibleGrandWordShown: string | null;
  result: string | null;
  roomId: number | null;
  roundsBeforeFirstGrandAttempt: number | null;
  soloSessionId: string | null;
  syncedToSheets: Generated<boolean>;
  totalLettersCollected: Generated<number>;
  totalRounds: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  winningGrandAttempt: Generated<boolean>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  id: Generated<number>;
  success: Generated<boolean | null>;
  usernameLower: string;
}

export interface PendingGameLogs {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  logData: Json;
  logType: string;
  roomId: number;
}

export interface PlayerCategoryHistory {
  categoryName: string;
  gameNumber: Generated<number>;
  id: Generated<number>;
  isBaseCategory: Generated<boolean>;
  playerId: string;
  playerName: Generated<string | null>;
  usedAt: Generated<Timestamp | null>;
}

export interface RoomPlayers {
  collectedLetters: Generated<string[] | null>;
  id: Generated<number>;
  isReady: Generated<boolean>;
  joinedAt: Generated<Timestamp>;
  lastSeenAt: Generated<Timestamp>;
  playerId: string;
  playerName: string;
  roomId: number;
  tutorialComplete: Generated<boolean>;
}

export interface Rooms {
  baseCategory: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  currentMiniCategory: string | null;
  failedRounds: Generated<number>;
  hostId: string;
  id: Generated<number>;
  letters: Generated<string[] | null>;
  maxPlayers: Generated<number>;
  minPlayers: Generated<number>;
  preferredPlayers: Generated<number>;
  roomType: Generated<RoomType>;
  roundNumber: Generated<number>;
  roundStartTime: Timestamp | null;
  roundWinnerId: string | null;
  roundWinningWord: string | null;
  shuffleVotes: Generated<string[] | null>;
  status: Generated<RoomStatus>;
  updatedAt: Generated<Timestamp>;
  usedMiniCategoryIds: Generated<string[] | null>;
}

export interface RoundHistory {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  letters: string[];
  miniCategory: string | null;
  roomId: number;
  roundNumber: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UsedWords {
  category: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  playerId: string;
  roomId: number;
  roundNumber: number;
  word: string;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  activeRoomId: number | null;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string | null;
  id: Generated<number>;
  role: Generated<string>;
  username: string;
  usernameLower: string;
}

export interface WordCategoryStats {
  category: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  lastSyncedAt: Timestamp | null;
  totalAcceptedCount: Generated<number>;
  uniqueUserIds: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
  word: string;
}

export interface WordSubmissions {
  category: string;
  createdAt: Generated<Timestamp | null>;
  fitsCategory: boolean;
  id: Generated<number>;
  isBaseCategory: Generated<boolean>;
  isValid: boolean;
  playerId: string;
  playerName: Generated<string | null>;
  roomId: number | null;
  word: string;
}

export interface WordValidationCache {
  category: string;
  createdAt: Generated<Timestamp | null>;
  definition: string | null;
  fitsCategory: boolean | null;
  id: Generated<number>;
  isValid: boolean;
  normalizedWord: string;
  rejectionReason: string | null;
  updatedAt: Generated<Timestamp | null>;
  validationSource: string | null;
  word: string;
}

export interface DB {
  categoryLetterHistory: CategoryLetterHistory;
  categoryStats: CategoryStats;
  gameSessionStats: GameSessionStats;
  loginAttempts: LoginAttempts;
  pendingGameLogs: PendingGameLogs;
  playerCategoryHistory: PlayerCategoryHistory;
  roomPlayers: RoomPlayers;
  rooms: Rooms;
  roundHistory: RoundHistory;
  sessions: Sessions;
  usedWords: UsedWords;
  userPasswords: UserPasswords;
  users: Users;
  wordCategoryStats: WordCategoryStats;
  wordSubmissions: WordSubmissions;
  wordValidationCache: WordValidationCache;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const RoomTypeArrayValues: [RoomType, ...RoomType[]] = ["private","public"];
export const RoomStatusArrayValues: [RoomStatus, ...RoomStatus[]] = ["finished","playing","tutorial","waiting"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.